export const INSTITUTIONS = [
    {
        index: 0,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: 'https://ca.slack-edge.com/T0468SSBD-U02AEUYMMNU-547f0cc303a2-512',
    },
    {
        index: 1,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 2,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 3,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 4,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 5,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 6,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 7,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 8,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 9,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 10,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 11,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 12,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        index: 13,
        name: '한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
];
