export const INSTITUTIONS = [
    {
        id: '1-0',
        name: '1-0 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 2,
        logo: 'https://ca.slack-edge.com/T0468SSBD-U02AEUYMMNU-547f0cc303a2-512',
    },
    {
        id: '1-1',
        name: '1-1 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 1,
        logo: undefined,
    },
    {
        id: '1-2',
        name: '1-2 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 1,
        logo: undefined,
    },
    {
        id: '1-3',
        name: '1-3 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-4',
        name: '1-4 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-5',
        name: '1-5 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-6',
        name: '1-6 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-7',
        name: '1-7 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-8',
        name: '1-8 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 0,
        logo: undefined,
    },
    {
        id: '1-9',
        name: '1-9 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 20,
        logo: undefined,
    },
    {
        id: '1-10',
        name: '1-10 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 20,
        logo: undefined,
    },

    {
        id: '2-0',
        name: '2-0 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: 'https://ca.slack-edge.com/T0468SSBD-U02AEUYMMNU-547f0cc303a2-512',
    },
    {
        id: '2-1',
        name: '2-1 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-2',
        name: '2-2 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-3',
        name: '2-3 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-4',
        name: '2-4 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-5',
        name: '2-5 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-6',
        name: '2-6 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-7',
        name: '2-7 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-8',
        name: '2-8 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-9',
        name: '2-9 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
    {
        id: '2-10',
        name: '2-10 한국청소년교육사회적협동조합한국청소년교육사회적협동조합',
        programCount: 10,
        logo: undefined,
    },
];
